name: freqtrade-bot
services:
  - name: freqtrade
    dockerfile_path: Dockerfile.deploy
    source_dir: /
    github:
      branch: main
      deploy_on_push: true
    envs:
      - key: EXCHANGE_KEY
        scope: RUN_TIME
        type: SECRET
      - key: EXCHANGE_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: TELEGRAM_TOKEN
        scope: RUN_TIME
        value: "7639884988:AAGymv6JJ7XtJOsqWg3tCoYW7js1r-rZPKw"
        type: SECRET
      - key: TELEGRAM_CHAT_ID
        scope: RUN_TIME
        value: "131817056"
        type: SECRET
